package ua.taras.kushmyruk.util;

public final class Parameters {
  public static final String PAGE = "page";
  public static final String USERNAME = "username";
  public static final String PASSWORD ="password";
  public static final String EMAIL = "email";
  public static final String USER_AUTH = "userAuth";
  public static final String ROLE = "role";
  public static final String LANGUAGE = "lang";
  public static final String EN = "en";
  public static final String EN_US = "en_US";
  public static final String UK_UA = "uk_UA";
  public static final String EXCEPTION = "exception";
  public static final String USER = "user";
  public static final String PATH_PREFIX = "WEB-INF/jsp/";
  public static final String PATH_SUFFIX = ".jsp";
  public static final String ADMIN_PARAM = "admin";
  public static final String TOUR_NAME = "tourName";
  public static final String PRICE = "price";
  public static final String COUNT_OF_PEOPLE = "countOfPeople";
  public static final String START_DATE = "startDate";
  public static final String END_DATE = "endDate";
  public static final String DEPARTING_FROM = "departingFrom";
  public static final String LOCALITY = "locality";
  public static final String COUNTRY = "country";
  public static final String HOTEL_NAME = "hotelName";
  public static final String TOUR_TYPE = "tourType";
  public static final String TOUR_STATUS = "tourStatus";
  public static final String ROOM_TYPE = "roomType";
  public static final String HOTEL_STARS = "hotelStars";
  public static final String IS_ALL_INCLUSIVE = "isAllInclusive";
  public static final String IS_HOT = "isHot";
  public static final String NOT_BOUGHT_TOURS = "notBoughtTours";
  public static final String TOUR = "tour";
  public static final String TOUR_BUY = "tourBuy";
  public static final String USER_LIST = "userList";
  public static final String METHOD = "method";
  public static final String CARD_NUMBER = "cardNumber";
  public static final String CARD_PASSWORD = "cardPassword";
  public static final String REPLENISH = "replenish";
  public static final String USER_TOURS = "userTours";
  public static final String REDACT = "redact";
}
